runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: yes

handlers:

- url: /v1/worker/.*
  script: naziscore.worker.app
  login: admin

- url: .*
  script: naziscore.main.app

libraries:
- name: webapp2
  version: latest
- name: yaml
  version: latest
